name: example
description: Android Strings To Flutter
version: 0.0.1
homepage: https://github.com/eyeem/as2f
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  as2f:
    path: '../'
