name: as2f
description: Android Strings To Flutter. Takes Android XML files with translations and creates i18n Dart classes out of them to be used inside Flutter projects.
version: 0.1.5
homepage: https://github.com/vishna/as2f
environment:
  sdk: ">=2.1.0 <3.0.0"